name: Build Video Library App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build all platforms
        run: |
          npm run build:mac-x64
          npm run build:mac-arm64
          npm run build:win
      
      - name: Upload macOS Intel artifact
        uses: actions/upload-artifact@v3
        with:
          name: Video-Library-macOS-x64
          path: dist/Video Library-darwin-x64
          
      - name: Upload macOS ARM artifact
        uses: actions/upload-artifact@v3
        with:
          name: Video-Library-macOS-arm64
          path: dist/Video Library-darwin-arm64
          
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: Video-Library-Windows
          path: dist/win-unpacked/
          
      - name: Create ZIP files
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          if [ -d "dist/Video Library-darwin-x64" ]; then
            cd dist && zip -r ../Video-Library-macOS-x64.zip "Video Library-darwin-x64" && cd ..
          fi
          if [ -d "dist/Video Library-darwin-arm64" ]; then
            cd dist && zip -r ../Video-Library-macOS-arm64.zip "Video Library-darwin-arm64" && cd ..
          fi
          if [ -d "dist/win-unpacked" ]; then
            cd dist && zip -r ../Video-Library-Windows.zip win-unpacked && cd ..
          fi
          
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            Video-Library-macOS-x64.zip
            Video-Library-macOS-arm64.zip
            Video-Library-Windows.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 